/* SQL QUERIES */

-- TABLES:
SELECT * FROM CUSTOMER;
SELECT * FROM BRANCH;
SELECT * FROM MONTHLYREVENUE;
SELECT * FROM ACCOUNT_CUSTOMER;
SELECT * FROM CUSTOMER_PHONENO;
SELECT * FROM LOGIN_CUSTOMER;
SELECT * FROM ORDER_RATE_BRANCH_CUSTOMER;
SELECT * FROM RATE;

-- TO VIEW ALL CUSTOMER DETAILS
SELECT * FROM CUSTOMER;

-- TO VIEW AMOUNT OWED FROM BITSID
SELECT OWE FROM ACCOUNT_CUSTOMER A_C
WHERE A_C.BITSID = BITSID;
	-- TEST QUERY
    SELECT OWE FROM ACCOUNT_CUSTOMER A_C
	WHERE A_C.BITSID = '2019B1A71039P';

-- TO REGISTER NEW CUSTOMER
CALL REG_CUST(BITSID,CUSTNAME,HOSTEL,ROOMNO,ACCOUNTID,PHONENO,LOGINID,PWD,USERNAME);
	-- TEST QUERY
    CALL REG_CUST('2019B1A10001P','Anand Rai','ML',205,'ACC78','9999199345','ID99','ananad','anand');

-- TO INPUT NEW LAUNDRY ORDER
CALL NEW_ORDER(ORDERID,BITSID,TYPEID,BRANCHID,LAUNDRYWEIGHT,MONTH,YEAR);
	-- TEST QUERY
    CALL NEW_ORDER('ORD991','2019B1A71039P','CLOTHES123','CVR123',2,'APR',2022);

-- TO MAKE DELIVERY
CALL COMPLETE_DELIVERY(ORDERID);
	-- TEST QUERY
	CALL COMPLETE_DELIVERY('ORD991');

-- TO VIEW MONTHLY REVENUE OF A BRANCH
SELECT MONTH,YEAR,INCOME FROM MONTHLYREVENUE MR
WHERE MR.BRANCHID = BRANCHID;
	-- TEST QUERY
	SELECT MONTH,YEAR,INCOME FROM MONTHLYREVENUE MR
	WHERE MR.BRANCHID = 'CVR123';

-- TO VIEW ORDER STATUS FOR A CUSTOMER
SELECT ORDERID, STATUS FROM ORDER_RATE_BRANCH_CUSTOMER ORBC
WHERE ORBC.BITSID = BITSID;
	-- TEST QUERY
	SELECT ORDERID, STATUS FROM ORDER_RATE_BRANCH_CUSTOMER ORBC
	WHERE ORBC.BITSID = '2019B1A71039P';


-- TO VIEW ORDERS FROM A HOSTEL
SELECT * FROM ORDER_RATE_BRANCH_CUSTOMER ORBC
WHERE ORBC.BITSID = (SELECT BITSID FROM CUSTOMER WHERE CUSTOMER.HOSTEL = HOSTEL);
	-- TEST QUERY
	SELECT * FROM ORDER_RATE_BRANCH_CUSTOMER ORBC
	WHERE ORBC.BITSID IN(SELECT BITSID FROM CUSTOMER WHERE CUSTOMER.HOSTEL = 'VK');

-- TO VIEW ALL PENDING ORDERS
SELECT ORDERID, STATUS FROM ORDER_RATE_BRANCH_CUSTOMER ORBC
WHERE ORBC.STATUS = "PENDING";

-- TO VIEW CUSTOMERS OF A PARTICULAR BRANCH
SELECT BITSID,CUSTNAME FROM CUSTOMER CST
WHERE CST.BITSID = (SELECT BITSID FROM ORDER_RATE_BRANCH_CUSTOMER ORBC WHERE ORBC.BRANCHID = BRANCHID);
	-- TEST QUERY
	SELECT BITSID,CUSTNAME FROM CUSTOMER CST
	WHERE CST.BITSID IN(SELECT BITSID FROM ORDER_RATE_BRANCH_CUSTOMER ORBC WHERE ORBC.BRANCHID = 'CVR123');

-- TO UPDATE MONTH IN MONTHLY REVENUE
CALL UPDATE_MONTH(BRANCHID,MONTH,YEAR);
	-- TEST QUERY
	CALL UPDATE_MONTH('CVR123','MAY',2022);

-- TO VIEW ALL ROOM NO IN KRISHNA BHAWAN REGISTERED IN LAUNDRY
SELECT ROOMNO FROM KRVIEW;

/*
START TRANSACTION;
DROP TABLE ACCOUNT_CUSTOMER;
DROP TABLE CUSTOMER_PHONENO;
DROP TABLE LOGIN_CUSTOMER;
DROP TABLE ORDER_RATE_BRANCH_CUSTOMER;
DROP TABLE MONTHLY_REVENUE;
DROP TABLE BRANCH;
DROP TABLE CUSTOMER;
DROP TABLE RATE;
DROP DATABASE LAUNDRY_MANAGEMENT_SYSTEM;
COMMIT;
*/

